
module algos @test;

// fn void t_InsertionSort() => @test_sort(gen_slice_killing_sorted()) { insertion_sort(gen_slice_killing()); };
// fn void t_InsertionSortRec() => @test_sort(gen_slice_killing_sorted()) { insertion_sort_rec(gen_slice_killing()); };
// fn void t_MergeSort() => @test_sort(gen_slice_killing_sorted()) { merge_sort(gen_slice_killing()); };
//
// fn void t_LinearSearch() => @test_search(7) { return linear_search(gen_slice_killing(), 10); };
// fn void t_BinarySearch() => @test_search(57) { return binary_search(gen_slice_killing_sorted(), 10); };

